### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Pgabrielmnecraft** [Sushutt/Infinite-Discoveries#1]
I was trying to make a new galaxy with 10 stars, 10~ planets per star, and 5~ moons per planet, but when the generation started, it stopped with this error:

log: 
[InfiniteDiscoveries.log](https://github.com/Sushutt/Infinite-Discoveries/files/11186889/InfiniteDiscoveries.log)

**Comment by Sushutt** [comment]
I'm guessing if you closed it then the issue resolved itself?

**Comment by Pgabrielmnecraft** [comment]
> I'm guessing if you closed it then the issue resolved itself?

yeah
